export default {
  "login": "JayantDwivedi",
  "id": 49179672,
  "node_id": "MDQ6VXNlcjQ5MTc5Njcy",
  "avatar_url": "https://avatars.githubusercontent.com/u/49179672?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JayantDwivedi",
  "html_url": "https://github.com/JayantDwivedi",
  "followers_url": "https://api.github.com/users/JayantDwivedi/followers",
  "following_url": "https://api.github.com/users/JayantDwivedi/following{/other_user}",
  "gists_url": "https://api.github.com/users/JayantDwivedi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JayantDwivedi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JayantDwivedi/subscriptions",
  "organizations_url": "https://api.github.com/users/JayantDwivedi/orgs",
  "repos_url": "https://api.github.com/users/JayantDwivedi/repos",
  "events_url": "https://api.github.com/users/JayantDwivedi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JayantDwivedi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Jayant Dwivedi",
  "company": null,
  "blog": "",
  "location": "Mathura,U.P.",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 46,
  "public_gists": 0,
  "followers": 16,
  "following": 19,
  "created_at": "2019-04-02T03:59:42Z",
  "updated_at": "2021-04-10T05:04:31Z"
};